### **Thông tin công ty**

In [23]:
from vnstock import Company
company = Company(symbol='VCB', source='TCBS')

In [24]:
company.overview()

,symbol,exchange,industry,company_type,no_shareholders,foreign_percent,outstanding_share,issue_share,established_year,no_employees,stock_rating,delta_in_week,delta_in_month,delta_in_year,short_name,website,industry_id,industry_id_v2
0,VCB,HOSE,Banks,NH,25183,0.216,8355.7,8355.7,2008,24306,2.6,0.012,-0.062,-0.29,Vietcombank,https://vietcombank.com.vn,289,8355

In [25]:
# Cổ đông
company.shareholders()

                share_holder  share_own_percent
0  The State Bank Of Vietnam             0.7480
1          Mizuho Bank, Ltd.             0.1500
2                      Other             0.0151

In [26]:
# Ban lãnh đạo 
company.officers(filter_by='working')

,officer_name,officer_position,officer_own_percent
8,Nguyen Danh Luong,Spokesman,0.0
11,Le Hoang Tung,Spokesman,0.0
13,Le Viet Anh,ROOT,0.0
14,Le Viet Anh,Person in charge of Corporate governace,0.0
9,Do Thi Mai Huong,Member of Supervisors Board,0.0
6,Nguyen Danh Luong,Member of Management Board,0.0
16,Le Thi Kim Nga,Member of Management Board,0.0
19,Nguyen Thi Kim Oanh,Member of Management Board,0.0
5,Nguyen Thanh Tung,Legal Representative,0.0
3,Phung Nguyen Hai Yen,Deputy General Director,0.0
7,Nguyen Danh Luong,Deputy General Director,0.0
10,Le Hoang Tung,Deputy General Director,0.0
18,NGUYEN VAN TUAN,Deputy General Director,0.0
15,Le Viet Anh,Company Secretary,0.0
4,Nguyen Thanh Tung,Chairman of Management Board,0.0
0,Dam Lam Thanh,None,0.0
1,Dau Thi Thuy Van,None,0.0
2,Nghiem Xuan Thanh,None,0.0
12,Nguyen My Hao,None,0.0
17,Dao Hao,None,0.0

In [27]:
# Công ty con
company.subsidiaries()

                                     sub_company_name  sub_own_percent
0   Vietnam Foreign Trade Joint Stock Bank Securit...            1.000
1   Money Transfer Company Limited Joint Stock Com...            1.000
2              Vietcombank Financial Leasing Co., Ltd            1.000
3     Vietnam Finance Company In Hong Kong - Vinafico            1.000
4                                    Vietnam Neo Bank            1.000
5       Foreign Trade Of Vietnam Bank Limited In Laos            1.000
6                                   Vcb Money Company            0.875
7                           Vietcombank Tower 198 Ltd            0.700
8   Vietcombank-bonday-benthanh Joint Venture Comp...            0.520
9         Vietcombank Fund Management Company Limited            0.510
10              FWD Vietnam Insurance Company Limited            0.450
11                 Vietcombank-bonday Company Limited            0.160
12                   Petrolimex Insurance Corporation            0.080
13  Vietnam Export Import Commercial Joint Stock Bank            0.045
14               Military Commercial Joint Stock Bank            0.043
15               Vietnam Airlines Joint Stock Company            0.010
16   PetroVietNam Driling & Well Services Corporation            0.002
17                 Orient Commercial Joint Stock Bank            0.000

In [28]:
company.events().head(3)

,rsi,rs,id,price,price_change,price_change_ratio,price_change_ratio_1m,event_name,event_code,notify_date,exer_date,reg_final_date,exer_right_date,event_desc
0,41.8,38.0,2601159,61554.0,-595.0,-0.010,-0.075,VCB - Pay cash dividend 2024 - Year at VND 450...,DIV,2025-09-30,2025-10-24,2025-10-06,2025-10-03,Joint Stock Commercial Bank For Foreign Trade ...
1,53.6,56.0,2600289,65227.0,-99.0,-0.002,0.051,VCB - Change Address,OTHE,2025-09-11,2025-09-03,1753-01-01,1753-01-01,Joint Stock Commercial Bank For Foreign Trade ...
2,66.8,56.0,2599774,67014.0,-1390.0,-0.020,0.098,VCB - Report Insider Transaction,DDINS,2025-09-05,2025-08-29,1753-01-01,1753-01-01,- Name of person/ corporation that conducts th...

In [29]:
company.news().head(3)

,rsi,rs,price,price_change,price_change_ratio,price_change_ratio_1m,id,title,source,publish_date
0,41.8,37.0,61653,-298,-0.005,-0.073,11728557,VCB: Nghị quyết HĐQT về việc phê duyệt chủ trư...,TCBS,2025-10-02 15:33:12
1,41.8,38.0,61554,-595,-0.010,-0.075,11725892,VCB: Thông báo về ngày đăng ký cuối cùng trả c...,TCBS,2025-09-30 13:35:33
2,42.0,39.0,62546,297,0.005,-0.009,11721351,VCB: Nghị quyết HĐQT về việc phê duyệt thanh t...,TCBS,2025-09-25 14:02:12

In [30]:
# Báo cáo phân tích
company.reports()

AttributeError: 'Company' object has no attribute 'reports'

In [ ]:
# tình hình tài chính
company.ratio_summary()

AttributeError: 'Company' object has no attribute 'ratio_summary'

In [ ]:
# Thống kê giao dịch
company.trading_stats()

AttributeError: 'Company' object has no attribute 'trading_stats'

In [ ]:
company.profile()

,symbol,company_name,company_profile,history_dev,company_promise,business_risk,key_developments,business_strategies
0,VCB,Joint Stock Commercial Bank For Foreign Trade ...,Joint Stock Commercial Bank For Foreign Trade...,"October 30, 1962: Bank for Foreign Trade of ...",None,Risks related to geopolitical instability and...,Account service Mobilizing capital service; ...,"As the leading bank in Vietnam, one of the..."

In [ ]:
# Lịch sử chia cổ tức
company.dividends().head(3)

  exercise_date  cash_year  cash_dividend_percentage issue_method
0    2025-10-03       2024                     0.045         cash
1    2025-03-12       2025                     0.495        share
2    2023-07-25       2023                     0.181        share

In [ ]:
# Giao dịch nội bộ
company.insider_deals().head(5)

,deal_announce_date,deal_method,deal_action,deal_quantity,deal_price,deal_ratio
0,2025-09-05,Cổ đông lớn,Bán,-58757.0,67014.0,-0.045
1,2025-05-15,Cổ đông nội bộ,Mua,20000.0,58277.0,0.098
2,2025-02-20,Cổ đông nội bộ,Mua,10000.0,60896.0,0.051
3,2023-12-21,Cổ đông nội bộ,Mua,5000.0,53724.0,0.191
4,2020-12-30,Cổ đông sáng lập,Bán,-2523.0,42618.0,0.502

### **Cổ phiếu:**

In [ ]:
from vnstock import Listing
listing = Listing(source='VCI')

In [ ]:
# Liệt kê mã CP
listing.all_symbols()

     symbol                                         organ_name
0       YTC  Công ty Cổ phần Xuất nhập khẩu Y tế Thành phố ...
1       YEG                     Công ty Cổ phần Tập đoàn Yeah1
2       YBM     Công ty Cổ phần Khoáng sản Công nghiệp Yên Bái
3       YBC      Công ty Cổ phần Xi măng và Khoáng sản Yên Bái
4       XPH                    Công ty Cổ phần Xà phòng Hà Nội
...     ...                                                ...
1714    AAS            Công ty Cổ phần Chứng khoán SmartInvest
1715    AAM                    Công ty Cổ Phần Thủy Sản MeKong
1716    AAH                           Công ty Cổ phần Hợp Nhất
1717    AAA                  Công ty Cổ phần Nhựa An Phát Xanh
1718    A32                                 Công ty Cổ phần 32

[1719 rows x 2 columns]

In [ ]:
# Liệt kê mã CP theo sàn
listing.symbols_by_exchange().head(5)

,symbol,exchange,type,organ_short_name,organ_name,product_grp_id
0,YTC,UPCOM,STOCK,XNK Y tế TP.HCM,Công ty Cổ phần Xuất nhập khẩu Y tế Thành phố ...,UPX
1,YEG,HSX,STOCK,Tập đoàn Yeah1,Công ty Cổ phần Tập đoàn Yeah1,STO
2,YBM,HSX,STOCK,Khoáng sản CN Yên Bái,Công ty Cổ phần Khoáng sản Công nghiệp Yên Bái,STO
3,YBC,UPCOM,STOCK,Xi măng và Khoáng sản Yên Bái,Công ty Cổ phần Xi măng và Khoáng sản Yên Bái,UPX
4,XPH,UPCOM,STOCK,Xà phòng Hà Nội,Công ty Cổ phần Xà phòng Hà Nội,UPX

- Liệt kê tất cả mã chứng khoán theo nhóm phân loại.

* HOSE, HNX, UPCOM
* VN30, VN100, HNX30
* VNMidCap, VNSmallCap, VNAllShare, HNXCon, HNXFin HNXLCap, HNXMSCap, HNXMan,
* ETF
* FU_INDEX (mã chỉ số hợp đồng tương lai)
* CW (chứng quyền)

In [ ]:
# Liệt kê mã CP theo phân nhóm
listing.symbols_by_group('HOSE')

0      AAA
1      AAM
2      AAT
3      ABR
4      ABS
      ...
408    VTB
409    VTO
410    VTP
411    YBM
412    YEG
Name: symbol, Length: 413, dtype: object

In [ ]:
# CP theo ngành ICB
listing.symbols_by_industries().head(3)

,symbol,organ_name,icb_name3,icb_name2,icb_name4,com_type_code,icb_code1,icb_code2,icb_code3,icb_code4
0,F88,Công ty Cổ phần Đầu tư F88,Dịch vụ tài chính,Dịch vụ tài chính,Tài chính cá nhân,CT,8000,8700,8770,8773
1,DVT,Trung tâm Đào tạo nghiệp vụ Giao thông vận tải...,Tư vấn & Hỗ trợ Kinh doanh,Hàng & Dịch vụ Công nghiệp,Đào tạo & Việc làm,CT,2000,2700,2790,2793
2,AFX,Công ty Cổ phần Xuất Nhập khẩu Nông sản Thực p...,Phân phối thực phẩm & dược phẩm,Bán lẻ,Phân phối thực phẩm,CT,5000,5300,5330,5337

In [ ]:
# Danh sách ngành ICB
listing.industries_icb().head(3)

,icb_name,en_icb_name,icb_code,level
0,Sản xuất Dầu khí,Oil & Gas Producers,0530,3
1,"Thiết bị, Dịch vụ và Phân phối Dầu khí","Oil Equipment, Services & Distribution",0570,3
2,Hóa chất,Chemicals,1350,3

### **Thống kê giá lịch sử:**

In [ ]:
from vnstock import Quote
quote = Quote(symbol='VCI', source='VCI')

In [ ]:
quote.history(start='2025-10-06', end='2025-10-07')

        time  open  high   low  close    volume
0 2025-10-06  42.1  44.5  42.1   44.5  10258700

In [ ]:
# Dữ liệu khớp lệnh
quote.intraday()

RetryError: RetryError[<Future at 0x2323f809850 state=finished raised ValueError>]

### **Báo cáo tài chính**

In [2]:
!pip install vnstock

Requirement already satisfied: vnstock in C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (3.2.6)
Requirement already satisfied: requests in C:\Users\admin\AppData\Roaming\Python\Python311\site-packages (from vnstock) (2.32.2)
Requirement already satisfied: beautifulsoup4 in C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from vnstock) (4.13.5)
Requirement already satisfied: pandas in C:\Users\admin\AppData\Roaming\Python\Python311\site-packages (from vnstock) (2.1.4)
Requirement already satisfied: seaborn in C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from vnstock) (0.13.2)
Requirement already satisfied: openpyxl in C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from vnstock) (3.1.5)
Requirement already satisfied: pydantic in C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from vnstock) (2.11.7)
Requirement already satisfied: psutil in C:\Users\admin\AppData\Roaming\Python\Python311\site-packages (from vnstock) (7.0.0)
Requirement already satisfied: fake_useragent in C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from vnstock) (2.2.0)
Requirement already satisfied: vnstock_ezchart in C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from vnstock) (0.0.2)
Requirement already satisfied: click in C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from vnstock) (8.2.1)
Requirement already satisfied: packaging>=20.0 in C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from vnstock) (24.2)
Requirement already satisfied: importlib-metadata>=1.0 in C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from vnstock) (8.7.0)
Requirement already satisfied: tenacity in C:\Users\admin\AppData\Roaming\Python\Python311\site-packages (from vnstock) (8.5.0)
Requirement already satisfied: vnai>=2.0.3 in C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from vnstock) (2.1.9)
Requirement already satisfied: zipp>=3.20 in C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from importlib-metadata>=1.0->vnstock) (3.23.0)
Requirement already satisfied: charset-normalizer<4,>=2 in C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from requests->vnstock) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from requests->vnstock) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from requests->vnstock) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from requests->vnstock) (2025.8.3)
Requirement already satisfied: soupsieve>1.2 in C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from beautifulsoup4->vnstock) (2.8)
Requirement already satisfied: typing-extensions>=4.0.0 in C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from beautifulsoup4->vnstock) (4.14.1)
Requirement already satisfied: colorama in C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from click->vnstock) (0.4.6)
Requirement already satisfied: et-xmlfile in C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from openpyxl->vnstock) (2.0.0)
Requirement already satisfied: numpy<2,>=1.23.2 in C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pandas->vnstock) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pandas->vnstock) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pandas->vnstock) (2025.2)
Requirement already satisfied: tzdata>=2022.1 in C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pandas->vnstock) (2025.2)
Requirement already satisfied: six>=1.5 in C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from python-dateutil>=2.8.2->pandas->vnstock) (1.17.0)
Requirement already satisfied: annotated-types>=0.6.0 in C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pydantic->vnstock) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pydantic->vnstock) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pydantic->vnstock) (0.4.1)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from seaborn->vnstock) (3.10.6)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn->vnstock) (1.3.3)
Requirement already satisfied: cycler>=0.10 in C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn->vnstock) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn->vnstock) (4.59.2)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn->vnstock) (1.4.9)
Requirement already satisfied: pillow>=8 in C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn->vnstock) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn->vnstock) (3.2.3)
Requirement already satisfied: squarify in C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from vnstock_ezchart->vnstock) (0.4.4)
Requirement already satisfied: wordcloud in C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from vnstock_ezchart->vnstock) (1.9.4)

In [2]:
import sys
print(sys.executable)

c:\Users\admin\AppData\Local\Programs\Python\Python310\python.exe

In [3]:
import sys
!{sys.executable} -m pip install vnstock==3.4.0

Collecting vnstock==3.4.0
  Using cached vnstock-3.4.0-py3-none-any.whl.metadata (49 kB)
Requirement already satisfied: requests in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from vnstock==3.4.0) (2.32.5)
Requirement already satisfied: beautifulsoup4 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from vnstock==3.4.0) (4.13.5)
Requirement already satisfied: pandas in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from vnstock==3.4.0) (2.3.2)
Collecting seaborn (from vnstock==3.4.0)
  Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: openpyxl in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from vnstock==3.4.0) (3.1.5)
Requirement already satisfied: pydantic in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from vnstock==3.4.0) (2.11.7)
Requirement already satisfied: psutil in c:\users\admin\appdata\roaming\python\python310\site-packages (from vnstock==3.4.0) (7.0.0)
Requirement already satisfied: packaging>=20.0 in c:\users\admin\appdata\roaming\python\python310\site-packages (from vnstock==3.4.0) (25.0)
Collecting importlib-metadata>=1.0 (from vnstock==3.4.0)
  Using cached importlib_metadata-9.0.0-py3-none-any.whl.metadata (4.5 kB)
Requirement already satisfied: tenacity in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from vnstock==3.4.0) (9.1.2)
Collecting vnai>=2.3.9 (from vnstock==3.4.0)
  Using cached vnai-2.5.0-py3-none-any.whl.metadata (691 bytes)
Collecting vnstock_ezchart>=0.0.3 (from vnstock==3.4.0)
  Using cached vnstock_ezchart-1.0.2-py3-none-any.whl.metadata (20 kB)
Collecting zipp>=3.20 (from importlib-metadata>=1.0->vnstock==3.4.0)
  Using cached zipp-4.1.0-py3-none-any.whl.metadata (3.6 kB)
Requirement already satisfied: cffi>=1.17.1 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from vnai>=2.3.9->vnstock==3.4.0) (1.17.1)
Requirement already satisfied: pycparser in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from cffi>=1.17.1->vnai>=2.3.9->vnstock==3.4.0) (2.22)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from requests->vnstock==3.4.0) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from requests->vnstock==3.4.0) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from requests->vnstock==3.4.0) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from requests->vnstock==3.4.0) (2025.8.3)
Requirement already satisfied: numpy<2.3,>=1.24 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from vnstock_ezchart>=0.0.3->vnstock==3.4.0) (2.2.6)
Collecting matplotlib>=3.5.0 (from vnstock_ezchart>=0.0.3->vnstock==3.4.0)
  Downloading matplotlib-3.10.9-cp310-cp310-win_amd64.whl.metadata (52 kB)
INFO: pip is looking at multiple versions of vnstock-ezchart to determine which version is compatible with other requirements. This could take a while.
Collecting vnstock_ezchart>=0.0.3 (from vnstock==3.4.0)
  Using cached vnstock_ezchart-1.0.1-py3-none-any.whl.metadata (20 kB)
  Using cached vnstock_ezchart-0.0.3-py3-none-any.whl.metadata (9.3 kB)
Collecting squarify (from vnstock_ezchart>=0.0.3->vnstock==3.4.0)
  Using cached squarify-0.4.4-py3-none-any.whl.metadata (600 bytes)
Collecting wordcloud (from vnstock_ezchart>=0.0.3->vnstock==3.4.0)
  Downloading wordcloud-1.9.6-cp310-cp310-win_amd64.whl.metadata (3.5 kB)
Requirement already satisfied: soupsieve>1.2 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from beautifulsoup4->vnstock==3.4.0) (2.7)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\admin\appdata\roaming\python\python310\site-packages (from beautifulsoup4->vnstock==3.4.0) (4.14.1)
Requirement already satisfied: et-xmlfile in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from openpyxl->vnstock==3.4.0) (2.0.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\admin\appdata\roaming\python\python310\site-packages (from pandas->vnstock==3.4.0) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from pandas->vnstock==3.4.0) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from pandas->vnstock==3.4.0) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\admin\appdata\roaming\python\python310\site-packages (from python-dateutil>=2.8.2->pandas->vnstock==3.4.0) (1.17.0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from pydantic->vnstock==3.4.0) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from pydantic->vnstock==3.4.0) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from pydantic->vnstock==3.4.0) (0.4.1)
Collecting contourpy>=1.0.1 (from matplotlib>=3.5.0->vnstock_ezchart>=0.0.3->vnstock==3.4.0)
  Downloading contourpy-1.3.2-cp310-cp310-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib>=3.5.0->vnstock_ezchart>=0.0.3->vnstock==3.4.0)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib>=3.5.0->vnstock_ezchart>=0.0.3->vnstock==3.4.0)
  Downloading fonttools-4.63.0-cp310-cp310-win_amd64.whl.metadata (121 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib>=3.5.0->vnstock_ezchart>=0.0.3->vnstock==3.4.0)
  Downloading kiwisolver-1.5.0-cp310-cp310-win_amd64.whl.metadata (5.2 kB)
Requirement already satisfied: pillow>=8 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from matplotlib>=3.5.0->vnstock_ezchart>=0.0.3->vnstock==3.4.0) (11.3.0)
Collecting pyparsing>=3 (from matplotlib>=3.5.0->vnstock_ezchart>=0.0.3->vnstock==3.4.0)
  Using cached pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Using cached vnstock-3.4.0-py3-none-any.whl (273 kB)
Using cached importlib_metadata-9.0.0-py3-none-any.whl (27 kB)
Using cached vnai-2.5.0-py3-none-any.whl (52 kB)
Using cached vnstock_ezchart-0.0.3-py3-none-any.whl (15 kB)
Using cached zipp-4.1.0-py3-none-any.whl (10 kB)
Using cached seaborn-0.13.2-py3-none-any.whl (294 kB)
Downloading matplotlib-3.10.9-cp310-cp310-win_amd64.whl (8.2 MB)
   ---------------------------------------- 0.0/8.2 MB ? eta -:--:--
   ------------------------------ --------- 6.3/8.2 MB 38.6 MB/s eta 0:00:01
   -------------------------------------- - 7.9/8.2 MB 19.4 MB/s eta 0:00:01
   ---------------------------------------- 8.2/8.2 MB 17.5 MB/s  0:00:00
Downloading contourpy-1.3.2-cp310-cp310-win_amd64.whl (221 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.63.0-cp310-cp310-win_amd64.whl (1.6 MB)
   ---------------------------------------- 0.0/1.6 MB ? eta -:--:--
   ---------------------------------------- 1.6/1.6 MB 27.8 MB/s  0:00:00
Downloading kiwisolver-1.5.0-cp310-cp310-win_amd64.whl (73 kB)
Using cached pyparsing-3.3.2-py3-none-any.whl (122 kB)
Using cached squarify-0.4.4-py3-none-any.whl (4.1 kB)
Downloading wordcloud-1.9.6-cp310-cp310-win_amd64.whl (306 kB)
Installing collected packages: squarify, zipp, pyparsing, kiwisolver, fonttools, cycler, contourpy, vnai, matplotlib, importlib-metadata, wordcloud, seaborn, vnstock_ezchart, vnstock

   -- -------------------------------------  1/14 [zipp]
   -- -------------------------------------  1/14 [zipp]
   ----- ----------------------------------  2/14 [pyparsing]
   ----- ----------------------------------  2/14 [pyparsing]
   ----- ----------------------------------  2/14 [pyparsing]
   ----- ----------------------------------  2/14 [pyparsing]
   ----- ----------------------------------  2/14 [pyparsing]
   -------- -------------------------------  3/14 [kiwisolver]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   ----------- ----------------------------  4/14 [fonttools]
   -------------- -------------------------  5/14 [cycler]
   ----------------- ----------------------  6/14 [contourpy]
   ----------------- ----------------------  6/14 [contourpy]
   ----------------- ----------------------  6/14 [contourpy]
   -------------------- -------------------  7/14 [vnai]
   -------------------- -------------------  7/14 [vnai]
   -------------------- -------------------  7/14 [vnai]
   -------------------- -------------------  7/14 [vnai]
   -------------------- -------------------  7/14 [vnai]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]
   ---------------------- -----------------  8/14 [matplotlib]

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
%pip install --upgrade vnstock

Requirement already satisfied: vnstock in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (3.4.0)
Collecting vnstock
  Using cached vnstock-4.0.4-py3-none-any.whl.metadata (59 kB)
Requirement already satisfied: requests in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from vnstock) (2.32.5)
Requirement already satisfied: beautifulsoup4 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from vnstock) (4.13.5)
Requirement already satisfied: pandas in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from vnstock) (2.3.2)
Requirement already satisfied: seaborn in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from vnstock) (0.13.2)
Requirement already satisfied: openpyxl in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from vnstock) (3.1.5)
Requirement already satisfied: pydantic in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from vnstock) (2.11.7)
Requirement already satisfied: psutil in c:\users\admin\appdata\roaming\python\python310\site-packages (from vnstock) (7.0.0)
Requirement already satisfied: packaging>=20.0 in c:\users\admin\appdata\roaming\python\python310\site-packages (from vnstock) (25.0)
Requirement already satisfied: importlib-metadata>=1.0 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from vnstock) (9.0.0)
Requirement already satisfied: tenacity in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from vnstock) (9.1.2)
Requirement already satisfied: vnai>=2.4.8 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from vnstock) (2.5.0)
Collecting vnstock_ezchart>=1.0.1 (from vnstock)
  Using cached vnstock_ezchart-1.0.2-py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: pytz in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from vnstock) (2025.2)
Requirement already satisfied: zipp>=3.20 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from importlib-metadata>=1.0->vnstock) (4.1.0)
Requirement already satisfied: cffi>=1.17.1 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from vnai>=2.4.8->vnstock) (1.17.1)
Requirement already satisfied: pycparser in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from cffi>=1.17.1->vnai>=2.4.8->vnstock) (2.22)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from requests->vnstock) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from requests->vnstock) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from requests->vnstock) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from requests->vnstock) (2025.8.3)
Requirement already satisfied: numpy<2.3,>=1.24 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from vnstock_ezchart>=1.0.1->vnstock) (2.2.6)
Requirement already satisfied: matplotlib>=3.5.0 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from vnstock_ezchart>=1.0.1->vnstock) (3.10.9)
Requirement already satisfied: cycler>=0.10.0 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from vnstock_ezchart>=1.0.1->vnstock) (0.12.1)
Collecting mplfinance>=0.12.9b5 (from vnstock_ezchart>=1.0.1->vnstock)
  Using cached mplfinance-0.12.10b0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\admin\appdata\roaming\python\python310\site-packages (from pandas->vnstock) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from pandas->vnstock) (2025.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from matplotlib>=3.5.0->vnstock_ezchart>=1.0.1->vnstock) (1.3.2)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from matplotlib>=3.5.0->vnstock_ezchart>=1.0.1->vnstock) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from matplotlib>=3.5.0->vnstock_ezchart>=1.0.1->vnstock) (1.5.0)
Requirement already satisfied: pillow>=8 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from matplotlib>=3.5.0->vnstock_ezchart>=1.0.1->vnstock) (11.3.0)
Requirement already satisfied: pyparsing>=3 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from matplotlib>=3.5.0->vnstock_ezchart>=1.0.1->vnstock) (3.3.2)
Requirement already satisfied: et-xmlfile in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from openpyxl->vnstock) (2.0.0)
Requirement already satisfied: six>=1.5 in c:\users\admin\appdata\roaming\python\python310\site-packages (from python-dateutil>=2.8.2->pandas->vnstock) (1.17.0)
Requirement already satisfied: soupsieve>1.2 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from beautifulsoup4->vnstock) (2.7)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\admin\appdata\roaming\python\python310\site-packages (from beautifulsoup4->vnstock) (4.14.1)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from pydantic->vnstock) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from pydantic->vnstock) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from pydantic->vnstock) (0.4.1)
Using cached vnstock-4.0.4-py3-none-any.whl (279 kB)
Using cached vnstock_ezchart-1.0.2-py3-none-any.whl (22 kB)
Using cached mplfinance-0.12.10b0-py3-none-any.whl (75 kB)
Installing collected packages: mplfinance, vnstock_ezchart, vnstock

   ---------------------------------------- 0/3 [mplfinance]
   ---------------------------------------- 0/3 [mplfinance]
   ---------------------------------------- 0/3 [mplfinance]
   ---------------------------------------- 0/3 [mplfinance]
   ---------------------------------------- 0/3 [mplfinance]
   ---------------------------------------- 0/3 [mplfinance]
  Attempting uninstall: vnstock_ezchart
   ---------------------------------------- 0/3 [mplfinance]
    Found existing installation: vnstock_ezchart 0.0.3
   ---------------------------------------- 0/3 [mplfinance]
    Uninstalling vnstock_ezchart-0.0.3:
   ---------------------------------------- 0/3 [mplfinance]
      Successfully uninstalled vnstock_ezchart-0.0.3
   ---------------------------------------- 0/3 [mplfinance]
   ------------- -------------------------- 1/3 [vnstock_ezchart]
  Attempting uninstall: vnstock
   ------------- -------------------------- 1/3 [vnstock_ezchart]
    Found existing installation: vnstock 3.4.0
   ------------- -------------------------- 1/3 [vnstock_ezchart]
   -------------------------- ------------- 2/3 [vnstock]
    Uninstalling vnstock-3.4.0:
   -------------------------- ------------- 2/3 [vnstock]
      Successfully uninstalled vnstock-3.4.0
   -------------------------- ------------- 2/3 [vnstock]
   -------------------------- ------------- 2/3 [vnstock]
   -------------------------- ------------- 2/3 [vnstock]
   -------------------------- ------------- 2/3 [vnstock]
   -------------------------- ------------- 2/3 [vnstock]
   -------------------------- ------------- 2/3 [vnstock]
   -------------------------- ------------- 2/3 [vnstock]
   -------------------------- ------------- 2/3 [vnstock]
   -------------------------- ------------- 2/3 [vnstock]
   -------------------------- ------------- 2/3 [vnstock]
   -------------------------- ------------- 2/3 [vnstock]
   -------------------------- ------------- 2/3 [vnstock]
   -------------------------- ------------- 2/3 [vnstock]
   -------------------------- ------------- 2/3 [vnstock]
   -------------------------- ------------- 2/3 [vnstock]
   -------------------------- ------------- 2/3 [vnstock]
   -------------------------- ------------- 2/3 [vnstock]
   -------------------------- ------------- 2/3 [vnstock]
   -------------------------- ------------- 2/3 [vnstock]
   -------------------------- ------------- 2/3 [vnstock]
   -------------------------- ------------- 2/3 [vnstock]
   -------------------------- ------------- 2/3 [vnstock]
   -------------------------- ------------- 2/3 [vnstock]
   -------------------------- ------------- 2/3 [vnstock]
   -------------------------- ------------- 2/3 [vnstock]
   -------------------------- ------------- 2/3 [vnstock]
   ---------------------------------------- 3/3 [vnstock]

Successfully installed mplfinance-0.12.10b0 vnstock-4.0.4 vnstock_ezchart-1.0.2
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
!python.exe -m pip install --upgrade pip

Requirement already satisfied: pip in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (26.1.1)
Collecting pip
  Using cached pip-26.1.2-py3-none-any.whl.metadata (4.6 kB)
Using cached pip-26.1.2-py3-none-any.whl (1.8 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 26.1.1
    Uninstalling pip-26.1.1:
      Successfully uninstalled pip-26.1.1
Successfully installed pip-26.1.2

In [6]:
import vnstock
print(vnstock.__version__)

AttributeError: module 'vnstock' has no attribute '__version__'

In [1]:
from vnstock import Finance
finance = Finance(symbol='VCI', source='VCI') # source = TCBS

In [2]:
# Báo cáo kết quả kinh doanh
finance.income_statement(period='year', lang='vi')

period,item,item_en,item_id,2025,2024,2023,2022
0,DOANH THU HOẠT ĐỘNG,OPERATING SALES,operating_sales,4.980202e+12,3.695525e+12,2.472461e+12,3.156243e+12
1,Các khoản giảm trừ doanh thu,Sales deductions,sales_deductions,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
2,Doanh thu thuần về hoạt động kinh doanh,Net sales,net_sales,4.980202e+12,3.695525e+12,2.472461e+12,3.156243e+12
3,CHI PHÍ HOẠT ĐỘNG,OPERATING EXPENSE,operating_expense,-2.390981e+12,-1.717402e+12,-1.063597e+12,-1.398531e+12
4,LỢI NHUẬN GỘP,GROSS PROFIT,gross_profit,2.589221e+12,1.978123e+12,1.408863e+12,1.757712e+12
...,...,...,...,...,...,...,...
74,Tổng thu nhập toàn diện,Total comprehensive income,total_comprehensive_income,1.663660e+12,1.675396e+12,1.069510e+12,2.334549e+11
75,Thu nhập toàn diện phân bổ cho chủ sở hữu,Comprehensive income distributed to shareholders,comprehensive_income_distributed_to_shareholders,1.663660e+12,1.675396e+12,1.069510e+12,2.334549e+11
76,Thu nhập toàn diện phân bổ cho cổ đông không n...,Comprehensive income distributed to uncontroll...,comprehensive_income_distributed_to_uncontroll...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
77,THU NHẬP THUẦN TRÊN CỔ PHIẾU PHỔ THÔNG,NET INCOME TO COMMON SHARE,net_income_to_common_share,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
78,THU NHẬP (LỖ) TOÀN DIỆN KHÁC SAU THUẾ,OTHER COMPREHENSIVE INCOME (LOSS) AFTER TAX,other_comprehensive_income_loss_after_tax,3.217052e+11,7.647038e+11,5.776054e+11,-6.355233e+11

In [3]:
# Bảng cân đối kế toán
finance.balance_sheet(period='year', lang='vi')

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

period,item,item_en,item_id,2025,2024,2023,2022
0,TÀI SẢN NGẮN HẠN,CURRENT ASSETS,current_assets,3.586891e+13,2.649184e+13,1.717445e+13,1.415769e+13
1,Tiền và tương đương tiền,Cash and cash equivalents,cash_and_cash_equivalents,3.213694e+12,4.743772e+12,7.878978e+11,3.423502e+12
2,Tiền,Cash,cash,3.213694e+12,4.743772e+12,5.378978e+11,2.313502e+12
3,Các khoản tương đương tiền,Cash equivalents,cash_equivalents,0.000000e+00,0.000000e+00,2.500000e+11,1.110000e+12
4,Các tài sản tài chính ghi nhận thông qua lãi l...,Financial assets at fair value through profit ...,financial_assets_at_fair_value_through_profit_...,2.237949e+12,8.462523e+11,1.221376e+11,6.652579e+11
...,...,...,...,...,...,...,...
203,Của Nhà đầu tư nước ngoài,Foreign investors,foreign_investors,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
204,Phải trả Tổ chức phát hành chứng khoán,Payable to securities issuers,payable_to_securities_issuers,0.000000e+00,8.324270e+11,0.000000e+00,0.000000e+00
205,Phải thu/phải trả của khách hàng về lỗi giao d...,Receivables from /Payables to customers for er...,receivables_from_payables_to_customers_for_err...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
206,Phải trả vay CTCK,Payable for securities company,payable_for_securities_company,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
207,"Phải trả cổ tức, gốc và lãi trái phiếu","Dividend, bond principal and interest payables",dividend_bond_principal_and_interest_payables,9.979740e+05,0.000000e+00,0.000000e+00,0.000000e+00

In [4]:
# báo cáo lưu chuyển tiền tệ
finance.cash_flow(od='year', lang='vi')

period,item,item_en,item_id,2026-Q1,2025-Q4,2025-Q3,2025-Q2
0,LỢI NHUẬN TRƯỚC THUẾ,NET PROFIT/(LOSS) BEFORE TAX,net_profit_loss_before_tax,4.038739e+11,5.436793e+11,5.189427e+11,2.114906e+11
1,Khấu hao tài sản cố định,Depreciation and amortization,depreciation_and_amortization,5.262260e+09,3.813820e+09,3.579860e+09,3.722357e+09
2,Các khoản dự phòng,Provisions,provisions,0.000000e+00,6.775200e+09,0.000000e+00,0.000000e+00
3,"Lãi, lỗ chênh lệch tỷ giá hối đoái chưa thực hiện",Unrealized foreign exchange gain/(loss),unrealized_foreign_exchange_gain_loss,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
4,"Lãi, lỗ hoạt động đầu tư",Profit/(loss) from investing activities,profit_loss_from_investing_activities,0.000000e+00,-3.650223e+08,0.000000e+00,-2.300000e+08
...,...,...,...,...,...,...,...
143,Tiền thu khác,Other receivables,other_receivables,0.000000e+00,6.170890e+09,0.000000e+00,0.000000e+00
144,Các khoản chi khác,Other expenses,other_expenses,-1.129931e+12,1.574700e+09,-8.800000e+05,-3.602200e+08
145,"(-) Tăng, (+) giảm chi phí phải trả (không bao...",Increase/ (decrease) in payable expenses (excl...,increase_decrease_in_payable_expenses_excludin...,-3.304575e+09,6.518539e+09,-3.413473e+09,3.720909e+09
146,Chi trả thanh toán giao dịch chứng khoán của k...,Cash outflow on securities transaction settlem...,cash_outflow_on_securities_transaction_settlem...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
147,Chi trả cho hoạt động ủy thác đầu tư của khách...,Cash outflow on customers' entrusted investmen...,cash_outflow_on_customers_entrusted_investment...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00

In [5]:
# Chỉ số tài chính
finance.ratio(period='year', lang='vi')

period,item,item_en,item_id,2018,2018,2018,2018,2018,2018,2018,2018,2018,2018,2018,2018,2018,2018,2018,2018
0,Năm,0,year,2018,2018,2018,2018,2018,2018,2018,2018,2018,2018,2018,2018,2018,2018,2018,2018
1,Quý,0,quarter,1,2,3,4,1,2,3,4,1,2,3,4,1,2,3,4
2,Mã TTM,Ratio TTM Id,ratioTTMId,2698852,2713040,2715800,2717078,2698852,2713040,2715800,2717078,2698852,2713040,2715800,2717078,2698852,2713040,2715800,2717078
3,Loại tỷ lệ,Ratio Type,ratioType,RATIO_TTM,RATIO_TTM,RATIO_TTM,RATIO_TTM,RATIO_TTM,RATIO_TTM,RATIO_TTM,RATIO_TTM,RATIO_TTM,RATIO_TTM,RATIO_TTM,RATIO_TTM,RATIO_TTM,RATIO_TTM,RATIO_TTM,RATIO_TTM
4,Số CP lưu hành (triệu),Outstanding Shares (mil),outstanding_shares,161999890,162999890,162999890,162949876,161999890,162999890,162999890,162949876,161999890,162999890,162999890,162949876,161999890,162999890,162999890,162949876
5,Vốn hóa,Market Cap,market_cap,8747994060000.0,9453993620000.0,6422195666000.0,5817310573200.0,8747994060000.0,9453993620000.0,6422195666000.0,5817310573200.0,8747994060000.0,9453993620000.0,6422195666000.0,5817310573200.0,8747994060000.0,9453993620000.0,6422195666000.0,5817310573200.0
6,Tỷ suất cổ tức (%),Dividend Yield (%),dividend_yield,0.0,0.0,0.017766,0.019608,0.0,0.0,0.017766,0.019608,0.0,0.0,0.017766,0.019608,0.0,0.0,0.017766,0.019608
7,P/E,P/E,pe_ratio,9.77776,10.298071,7.329572,7.073843,9.77776,10.298071,7.329572,7.073843,9.77776,10.298071,7.329572,7.073843,9.77776,10.298071,7.329572,7.073843
8,P/B,P/B,pb_ratio,1.804372,2.629041,1.701127,1.596856,1.804372,2.629041,1.701127,1.596856,1.804372,2.629041,1.701127,1.596856,1.804372,2.629041,1.701127,1.596856
9,P/S,P/S,ps_ratio,4.782772,4.78722,3.294845,3.193728,4.782772,4.78722,3.294845,3.193728,4.782772,4.78722,3.294845,3.193728,4.782772,4.78722,3.294845,3.193728
10,Giá/ Dòng tiền,Price/Cash Flow,price_to_cash_flow,-7.539719,-5.671215,-6.746206,16.007805,-7.539719,-5.671215,-6.746206,16.007805,-7.539719,-5.671215,-6.746206,16.007805,-7.539719,-5.671215,-6.746206,16.007805
11,EV/EBITDA,EV/EBITDA,ev_to_ebitda,8.101145,7.654437,5.343672,5.106902,8.101145,7.654437,5.343672,5.106902,8.101145,7.654437,5.343672,5.106902,8.101145,7.654437,5.343672,5.106902
12,Hệ số thanh toán tiền,Cash Ratio,cash_ratio,0.199635,0.23225,0.226279,0.570096,0.199635,0.23225,0.226279,0.570096,0.199635,0.23225,0.226279,0.570096,0.199635,0.23225,0.226279,0.570096
13,Hệ số thanh toán nhanh,Quick Ratio,quick_ratio,2.107552,1.886469,2.132656,2.335546,2.107552,1.886469,2.132656,2.335546,2.107552,1.886469,2.132656,2.335546,2.107552,1.886469,2.132656,2.335546
14,Hệ số thanh toán hiện hành,Current Ratio,current_ratio,2.107552,1.886469,2.132656,2.335546,2.107552,1.886469,2.132656,2.335546,2.107552,1.886469,2.132656,2.335546,2.107552,1.886469,2.132656,2.335546
15,Vốn chủ sở hữu,Owners Equity,owners_equity,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,Nợ/Vốn chủ,Debt/Equity,debtPerEquity,0.422878,0.405891,0.245588,0.270345,0.422878,0.405891,0.245588,0.270345,0.422878,0.405891,0.245588,0.270345,0.422878,0.405891,0.245588,0.270345
17,Nợ trên vốn chủ,Debt to Equity,debt_to_equity,0.99819,1.202236,0.952275,0.786999,0.99819,1.202236,0.952275,0.786999,0.99819,1.202236,0.952275,0.786999,0.99819,1.202236,0.952275,0.786999
18,ROE (%),ROE (%),roe,0.325467,0.283338,0.249307,0.246946,0.325467,0.283338,0.249307,0.246946,0.325467,0.283338,0.249307,0.246946,0.325467,0.283338,0.249307,0.246946
19,ROA (%),ROA (%),roa,0.151715,0.135681,0.120751,0.12742,0.151715,0.135681,0.120751,0.12742,0.151715,0.135681,0.120751,0.12742,0.151715,0.135681,0.120751,0.12742
20,Số ngày phải thu,Days Sales Outstanding,days_sales_outstanding,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21,Số ngày tồn kho,Days Inventory Outstanding,days_inventory_outstanding,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,Số ngày phải trả,Days Payable Outstanding,days_payable_outstanding,3.666598,3.654499,5.263445,2.723719,3.666598,3.654499,5.263445,2.723719,3.666598,3.654499,5.263445,2.723719,3.666598,3.654499,5.263445,2.723719
23,Biên LN gộp (%),Gross Margin (%),gross_margin,0.746005,0.731658,0.720567,0.74187,0.746005,0.731658,0.720567,0.74187,0.746005,0.731658,0.720567,0.74187,0.746005,0.731658,0.720567,0.74187
24,Biên EBIT (%),EBIT Margin (%),ebit_margin,0.682447,0.677145,0.668291,0.683812,0.682447,0.677145,0.668291,0.683812,0.682447,0.677145,0.668291,0.683812,0.682447,0.677145,0.668291,0.683812
25,Biên LN trước thuế (%),Pre-tax Profit Margin (%),pre_tax_profit_margin,0.582525,0.569016,0.551127,0.555294,0.582525,0.569016,0.551127,0.555294,0.582525,0.569016,0.551127,0.555294,0.582525,0.569016,0.551127,0.555294
26,Biên LN sau thuế (%),After-tax Profit Margin (%),net_margin,0.473283,0.461319,0.447088,0.451623,0.473283,0.461319,0.447088,0.451623,0.473283,0.461319,0.447088,0.451623,0.473283,0.461319,0.447088,0.451623
27,Vòng quay tài sản,Asset Turnover,asset_turnover,0.319379,0.294116,0.270083,0.282137,0.319379,0.294116,0.270083,0.282137,0.319379,0.294116,0.270083,0.282137,0.319379,0.294116,0.270083,0.282137
28,Biên lãi thuần,Net Interest Margin,net_interest_margin,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29,Lãi suất bình quân tài sản sinh lãi,Avg Yield on Earning Assets,avg_yield_on_earning_assets,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30,Chi phí vốn bình quân,Avg Cost of Financing,avg_cost_of_financing,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31,Thu nhập ngoài lãi,Non-interest Income,non_interest_income,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32,Tỷ lệ CIR,Cost/Income Ratio,cost_to_income_ratio,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
33,Tăng trưởng cho vay (%),Loans Growth (%),loans_growth,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
34,Tăng trưởng tiền gửi (%),Deposit Growth (%),deposit_growth,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
35,Vốn chủ/Tổng nợ,Equity/Total Liabilities,equity_to_liabilities,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
36,Vốn chủ/Cho vay,Equity/Loans,equity_to_loans,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
37,Vốn chủ/Tổng tài sản,Equity/Total Assets,equity_to_assets,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
38,LDR (%),LDR (%),ldr,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39,Nợ xấu (%),NPL (%),npl,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
40,DP rủi ro/Nợ xấu,Loan Loss Reserves/NPLs,loan_loss_reserves_to_npls,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
41,DP rủi ro/Cho vay,Loan Loss Reserve/Loans,loan_loss_reserve_to_loans,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
42,Trích lập DP/Cho vay,Provision/Outstanding Loans,provision_to_outstanding_loans,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
43,EBIT,EBIT,ebit,1248239892495.0,1337252681567.0,1302608545766.0,1245550187075.0,1248239892495.0,1337252681567.0,1302608545766.0,1245550187075.0,1248239892495.0,1337252681567.0,1302608545766.0,1245550187075.0,1248239892495.0,1337252681567.0,1302608545766.0,1245550187075.0
44,EBITDA,EBITDA,ebitda,1254219118788.0,1349014777672.0,1314623079471.0,1257128146781.0,1254219118788.0,1349014777672.0,1314623079471.0,1257128146781.0,1254219118788.0,1349014777672.0,1314623079471.0,1257128146781.0,1254219118788.0,1349014777672.0,1314623079471.0,1257128146781.0
45,ROIC,ROIC,roic,0.244276,0.264511,0.277008,0.269143,0.244276,0.264511,0.277008,0.269143,0.244276,0.264511,0.277008,0.269143,0.244276,0.264511,0.277008,0.269143
46,Chu kỳ tiền,Cash Cycle,cash_cycle,7.815772,6.301245,8.562445,8.609483,7.815772,6.301245,8.562445,8.609483,7.815772,6.301245,8.562445,8.609483,7.815772,6.301245,8.562445,8.609483
47,Vòng quay TS cố định,Fixed Asset Turnover,fixed_asset_turnover,79.115038,81.399569,89.148293,83.64526,79.115038,81.399569,89.148293,83.64526,79.115038,81.399569,89.148293,83.64526,79.115038,81.399569,89.148293,83.64526
48,Đòn bẩy tài chính,Financial Leverage,financial_leverage,0.99819,1.202236,0.952275,0.786999,0.99819,1.202236,0.952275,0.786999,0.99819,1.202236,0.952275,0.786999,0.99819,1.202236,0.952275,0.786999
49,CIR,CIR,cir,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
50,CAR,CAR,car,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
51,Vốn chủ sở hữu,Equity,equity,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
52,Tỷ lệ CASA,CASA Ratio,casa_ratio,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
53,Mã năm tỷ lệ,Ratio Year Id,ratioYearId,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

### Xuất dữ liệu thô:

In [6]:
# Khởi tạo class
from vnstock.explorer.vci import Finance
fin = Finance(symbol='PLX', period='quarter')

In [7]:
# Truy xuất báo cáo thô
fin._get_report(mode='raw').head()

ValueError: Loại báo cáo tài chính không hợp lệ: 'None'. Hỗ trợ: balance_sheet, income_statement, cash_flow, ratio

In [ ]:
# Truy xuất bảng tra cứu thuật ngữ 
fin._get_ratio_dict()

,field_name,name,en_name,type,order,unit,com_type_code
0,BSA1,TỔNG TÀI SẢN NGẮN HẠN,CURRENT ASSETS,Chỉ tiêu cân đối kế toán,12,tỷ,BH
1,BSA2,Tiền và tương đương tiền,Cash and cash equivalents,Chỉ tiêu cân đối kế toán,13,tỷ,BH
2,BSA5,Giá trị thuần đầu tư ngắn hạn,Net Short-term investment,Chỉ tiêu cân đối kế toán,14,tỷ,BH
3,BSA8,Các khoản phải thu,Accounts Receivables,Chỉ tiêu cân đối kế toán,15,tỷ,BH
4,BSA15,Hàng tồn kho ròng,Net Inventories,Chỉ tiêu cân đối kế toán,16,tỷ,BH
...,...,...,...,...,...,...,...
733,ebit,EBIT (Tỷ đồng),EBIT (Bn. VND),Chỉ tiêu khả năng sinh lợi,6,tỷ,NH
734,dividend,Tỷ suất cổ tức (%),Dividend yield (%),Chỉ tiêu khả năng sinh lợi,13,%,NH
735,RTQ17,Vòng quay hàng tồn kho,Inventory Turnover,Chỉ tiêu hiệu quả hoạt động,28,index,NH
736,fae,TSCĐ / Vốn CSH,Fixed Asset-To-Equity,Chỉ tiêu cơ cấu nguồn vốn,36,index,NH
737,charterCapitalRatio,Vốn CSH/Vốn điều lệ,Owners' Equity/Charter Capital,Chỉ tiêu cơ cấu nguồn vốn,38,index,NH

### **Bảng giá giao dịch**

In [8]:
from vnstock import Trading
trading = Trading()
trading.price_board(symbols_list=['VCB','ACB','TCB','BID'])

,symbol,time,exchange,ceiling_price,floor_price,reference_price,open_price,high_price,low_price,close_price,...,bid_vol_3,ask_price_1,ask_vol_1,ask_price_2,ask_vol_2,ask_price_3,ask_vol_3,foreign_buy_volume,foreign_sell_volume,foreign_room
0,VCB,1784536344760,HOSE,62500,54500,58500,58800,58800,56300,56700,...,254100,56800.0,9600,56900,48900,57000,136600,615877,3223586,821450731
1,ACB,1784536380474,HOSE,25150,21950,23550,23500,23500,22650,22850,...,287400,22850.0,19800,22900,70400,22950,63900,329900,873144,309851203
2,TCB,1784534401446,HOSE,33650,29250,31450,31400,31400,29950,29950,...,12900,30000.0,70800,30050,5100,30100,5000,343200,1388100,78739314
3,BID,1784536381975,HOSE,41500,36100,38800,38800,38900,37000,37000,...,15000,37100.0,200,37200,8000,37250,2300,22700,205741,907626069

In [ ]:
trading.price_board(symbols_list=['VCB','ACB','TCB','BID']).iloc[0].T

listing  symbol                                                                      VCB
         ceiling                                                                   66000
         floor                                                                     57400
         ref_price                                                                 61700
         stock_type                                                                STOCK
         exchange                                                                    HSX
         trading_status                                                TRADING_ACTIVATED
         trading_status_code                                                          20
         trading_status_group                                                          2
         security_status                                                               N
         last_trading_date                                                          None
         issue_date                                                                 None
         listed_share                                                         8355675094
         coupon_rate                                                                   0
         yield                                                                         0
         sending_time                                              20251006 01:44:21.890
         type                                                                      STOCK
         organ_name                    Ngân hàng Thương mại Cổ phần Ngoại thương Việt...
         mapping_symbol                                                             None
         product_grp_id                                                              STO
         partition                                                                     2
         index_type                                                                 None
         trading_date                                                         2025-10-06
         average_match_volume2_week                                              3890931
bid_ask  bid_count                                                                     0
         ask_count                                                                     0
match    accumulated_value                                                             0
         accumulated_volume                                                            0
         accumulated_value_g1                                                          0
         accumulated_volume_g1                                                         0
         avg_match_price                                                               0
         current_room                                                          702373672
         foreign_buy_volume                                                            0
         foreign_sell_volume                                                           0
         foreign_buy_value                                                   52893762800
         foreign_sell_value                                                  90271674200
         highest                                                                       0
         lowest                                                                        0
         match_price                                                                   0
         open_price                                                                 None
         first_time_match_price                                                     None
         match_type                                                                    b
         match_vol                                                                     0
         sending_time                                              20251006 07:45:05.230
         total_room                                                           2506702528
         total_buy_orders                                                              0
         total_sell_orders                                                             0
         bid_count                                                                     0
         ask_count                                                                     0
         underlying                                                                 None
         open_interest                                                              None
         stock_type                                                                STOCK
         partition                                                                     4
         is_match_price                                                            False
         ceiling_price                                                             66000
         floor_price                                                               57400
         reference_price                                                           61700
Name: 0, dtype: object

### **Bộ lọc cổ phiếu**

In [ ]:
from vnstock import Screener
screener_df = Screener().stock(params={"exchangeName": "HOSE,HNX,UPCOM"}, limit=1700)

In [ ]:
screener_df.head()

,ticker,exchange,industry,market_cap,roe,stock_rating,business_operation,business_model,financial_health,alpha,...,peg_forward,roa,npl,nim,price_vs_sma200,eps_recently,percent_price_vs_ma200,percent_price_vs_ma20,percent_price_vs_ma50,percent_price_vs_ma100
0,A32,UPCOM,Hàng cá nhân & Gia dụng,NaN,NaN,NaN,1.7,3.5,2.6,0.1,...,NaN,NaN,NaN,NaN,"{'vi': 'Giá cắt lên SMA(200)', 'en': 'Price cr...",NaN,0.0,2.0,0.7,-1.1
1,AAA,HSX,Hóa chất,3272.0,5.1,2.6,1.5,3.0,4.0,-0.1,...,-0.4,2.3,NaN,NaN,None,698.0,6.2,1.4,0.5,6.7
2,AAH,UPCOM,Tài nguyên Cơ bản,472.0,1.9,2.5,1.1,NaN,4.4,0.0,...,NaN,1.6,NaN,NaN,None,192.0,-4.2,-3.0,-4.7,-3.8
3,AAM,HSX,Thực phẩm và đồ uống,74.0,-0.1,NaN,1.1,NaN,4.2,0.0,...,NaN,-0.1,NaN,NaN,"{'vi': 'Giá cắt lên SMA(200)', 'en': 'Price cr...",-26.0,0.4,-0.8,-1.9,-0.6
4,AAS,UPCOM,Dịch vụ tài chính,2596.0,2.6,2.4,3.8,2.8,3.2,0.2,...,0.0,1.6,NaN,NaN,None,285.0,18.2,-3.5,-15.8,1.6

### **Dữ liệu quỹ mở**

In [ ]:
from vnstock import Fund
fund = Fund()

2025-10-07 07:44:20 - vnstock.explorer.fmarket.fund - INFO - Total number of funds currently listed on Fmarket: 58

In [ ]:
# Liệt kê quỹ
fund.listing().head(5)

2025-10-07 07:44:23 - vnstock.explorer.fmarket.fund - INFO - Total number of funds currently listed on Fmarket: 58

,short_name,name,fund_type,fund_owner_name,management_fee,inception_date,nav,nav_change_previous,nav_change_last_year,nav_change_inception,...,nav_change_3m,nav_change_6m,nav_change_12m,nav_change_24m,nav_change_36m,nav_change_36m_annualized,nav_update_at,fund_id_fmarket,fund_code,vsd_fee_id
0,DCDS,QUỸ ĐẦU TƯ CHỨNG KHOÁN NĂNG ĐỘNG DC,Quỹ cổ phiếu,CÔNG TY CỔ PHẦN QUẢN LÝ QUỸ DRAGON CAPITAL VIỆ...,1.95,2004-05-19,105123.62,-0.94,28.80,273.48,...,17.35,40.04,31.39,67.36,98.57,25.69,2025-10-06,28,VFMVF1,VFMVF1N001
1,BVFED,QUỸ ĐẦU TƯ CỔ PHIẾU NĂNG ĐỘNG BẢO VIỆT,Quỹ cổ phiếu,CÔNG TY TNHH QUẢN LÝ QUỸ BẢO VIỆT,1.00,2014-01-07,31039.00,-0.61,35.71,175.78,...,23.12,40.56,34.42,61.76,81.77,22.04,2025-10-06,12,BVFED,BVFEDN001
2,SSISCA,QUỸ ĐẦU TƯ LỢI THẾ CẠNH TRANH BỀN VỮNG SSI,Quỹ cổ phiếu,CÔNG TY TNHH QUẢN LÝ QUỸ SSI,1.75,2014-09-25,45383.92,-1.22,11.27,214.90,...,9.81,20.28,14.14,50.72,79.80,21.60,2025-10-06,11,SSISCA,SSISCAN001
3,MBVF,QUỸ ĐẦU TƯ GIÁ TRỊ MB CAPITAL,Quỹ cổ phiếu,CÔNG TY CỔ PHẦN QUẢN LÝ QUỸ ĐẦU TƯ MB,1.50,2014-04-24,27417.00,-0.45,23.31,91.90,...,11.08,26.78,25.01,52.88,73.66,20.20,2025-10-06,47,MBVF,MBVFN001
4,MAGEF,QUỸ ĐẦU TƯ CỔ PHIẾU TĂNG TRƯỞNG MIRAE ASSET VI...,Quỹ cổ phiếu,CÔNG TY TNHH QUẢN LÝ QUỸ MIREA ASSET VIỆT NAM,1.75,2019-07-22,21238.94,-0.76,24.58,112.39,...,20.88,35.55,24.55,55.15,70.82,19.54,2025-10-06,35,MAGEF,MAGEFN001

In [ ]:
# Tìm kiếm quỹ
fund.filter('DC')

   id shortName
0  40     VNDCF
1  67      DCIP
2  62    HDBOND
3  27      DCBF
4  25      DCDE
5  28      DCDS
6  29      DCAF

In [ ]:
# Báo cáo tăng trưởng NAV
fund.details.nav_report('SSISCA')

2025-10-07 07:44:29 - vnstock.explorer.fmarket.fund - INFO - Retrieving data for SSISCA

            date  nav_per_unit short_name
0     2017-01-04      14412.31     SSISCA
1     2017-01-11      14527.86     SSISCA
2     2017-01-18      14240.04     SSISCA
3     2017-01-25      14547.21     SSISCA
4     2017-01-31      14541.96     SSISCA
...          ...           ...        ...
1845  2025-09-30      46407.07     SSISCA
1846  2025-10-01      46048.41     SSISCA
1847  2025-10-02      46298.90     SSISCA
1848  2025-10-03      45944.84     SSISCA
1849  2025-10-06      45383.92     SSISCA

[1850 rows x 3 columns]

In [ ]:
# Danh mục đầu tư lớn
fund.details.top_holding('SSISCA')

2025-10-07 07:44:33 - vnstock.explorer.fmarket.fund - INFO - Retrieving data for SSISCA

,stock_code,industry,net_asset_percent,type_asset,update_at,fundId,short_name
0,MBB,Ngân hàng,9.05,STOCK,2025-09-09,11,SSISCA
1,CTG,Ngân hàng,7.35,STOCK,2025-09-09,11,SSISCA
2,TCB,Ngân hàng,7.23,STOCK,2025-09-09,11,SSISCA
3,MWG,Bán lẻ,6.32,STOCK,2025-09-09,11,SSISCA
4,HPG,Vật liệu xây dựng,6.19,STOCK,2025-09-09,11,SSISCA
5,VCB,Ngân hàng,4.55,STOCK,2025-09-09,11,SSISCA
6,ACB,Ngân hàng,4.51,STOCK,2025-09-09,11,SSISCA
7,KDH,Bất động sản,4.11,STOCK,2025-09-09,11,SSISCA
8,STB,Ngân hàng,4.06,STOCK,2025-09-09,11,SSISCA
9,GMD,Vận tải - Kho bãi,3.97,STOCK,2025-09-09,11,SSISCA

In [ ]:
# Phân bổ theo ngành
fund.details.industry_holding('SSISCA')

2025-10-07 07:44:45 - vnstock.explorer.fmarket.fund - INFO - Retrieving data for SSISCA

                    industry  net_asset_percent short_name
0                  Ngân hàng              36.75     SSISCA
1               Bất động sản              15.56     SSISCA
2                     Bán lẻ               6.32     SSISCA
3          Vật liệu xây dựng               6.19     SSISCA
4          Vận tải - Kho bãi               3.97     SSISCA
5     Công nghệ và thông tin               3.87     SSISCA
6              Thiết bị điện               3.69     SSISCA
7           Sản xuất Phụ trợ               3.38     SSISCA
8                Khai khoáng               2.55     SSISCA
9   Sản xuất Nhựa - Hóa chất               2.52     SSISCA
10                  Tiện ích               2.19     SSISCA
11       Thực phẩm - Đồ uống               1.91     SSISCA
12               Chứng khoán               1.86     SSISCA
13                  Bán buôn               1.06     SSISCA

In [ ]:
# Phân bổ theo tài sản
fund.details.asset_holding('SSISCA')

2025-10-07 07:44:49 - vnstock.explorer.fmarket.fund - INFO - Retrieving data for SSISCA

   asset_percent                asset_type short_name
0          91.82                  Cổ phiếu     SSISCA
1           8.18  Tiền và tương đương tiền     SSISCA

### **Dữ liệu thị trường, giá cả**

In [1]:
# Giá vàng SJC
from vnstock.explorer.misc.gold_price import *

c:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\vnai\scope\profile.py:562: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources

In [3]:
btmc_goldprice().tail(5)

,name,karat,gold_content,buy_price,sell_price,world_price,time
36,VÀNG NGUYÊN LIỆU (Vàng thị trường),24k,999.9,14580000,0,0,15/10/2025 10:04
25,VÀNG NGUYÊN LIỆU (Vàng thị trường),24k,999.9,14620000,0,0,15/10/2025 10:43
16,VÀNG NGUYÊN LIỆU (Vàng thị trường),24k,999.9,14670000,0,0,15/10/2025 11:29
10,VÀNG NGUYÊN LIỆU (Vàng thị trường),24k,999.9,14720000,0,0,15/10/2025 13:06
31,VÀNG NGUYÊN LIỆU (Vàng thị trường),24k,999.9,14580000,0,0,15/10/2025 10:05

In [ ]:
# tỉ giá ngoại tệ
from vnstock.explorer.misc.exchange_rate import *
vcb_exchange_rate(date='2025-10-07')

,currency_code,currency_name,buy _cash,buy _transfer,sell,date
2,AUD,AUSTRALIAN DOLLAR,"16,943.42","17,114.56","17,662.59",2025-10-07
3,CAD,CANADIAN DOLLAR,"18,411.77","18,597.74","19,193.26",2025-10-07
4,CHF,SWISS FRANC,"32,263.35","32,589.24","33,632.79",2025-10-07
5,CNY,CHINESE YUAN,"3,610.20","3,646.66","3,763.43",2025-10-07
6,DKK,DANISH KRONE,-,"4,060.95","4,216.21",2025-10-07
7,EUR,EURO,"30,096.79","30,400.80","31,683.37",2025-10-07
8,GBP,UK POUND STERLING,"34,518.94","34,867.61","35,984.11",2025-10-07
9,HKD,HONG KONG DOLLAR,"3,292.72","3,325.98","3,453.14",2025-10-07
10,INR,INDIAN RUPEE,-,295.49,308.21,2025-10-07
11,JPY,JAPANESE YEN,169.95,171.67,180.75,2025-10-07
12,KRW,KOREAN WON,16.17,17.96,19.49,2025-10-07
13,KWD,KUWAITI DINAR,-,"86,020.03","90,188.92",2025-10-07
14,MYR,MALAYSIAN RINGGIT,-,"6,192.53","6,327.22",2025-10-07
15,NOK,NORWEGIAN KRONE,-,"2,593.66","2,703.62",2025-10-07
16,RUB,RUSSIAN RUBLE,-,305.13,337.76,2025-10-07
17,SAR,SAUDI ARABIAN RIYAL,-,"6,993.20","7,294.13",2025-10-07
18,SEK,SWEDISH KRONA,-,"2,751.15","2,867.79",2025-10-07
19,SGD,SINGAPORE DOLLAR,"19,878.98","20,079.78","20,764.25",2025-10-07
20,THB,THAI BAHT,717.59,797.33,831.13,2025-10-07
21,USD,US DOLLAR,"26,153.00","26,183.00","26,403.00",2025-10-07

In [2]:
from modules.api import stock_api

# print(stock_api.get_index_detail("VN30"))
print(stock_api.get_stock_quote("FPT"))
# print(stock_api.get_history_prices("VCB", days=3))
# print(stock_api.format_stock_info("VCB"))

{'symbol': 'FPT', 'price': 95700.0, 'open': 97000.0, 'high': 103700.0, 'low': 90300.0, 'change': -1300.0, 'percent_change': -1.34, 'volume': 981000, 'timestamp': '23-10-2025 09:32:26', 'source': 'VNStock.Trading'}

In [1]:
from modules.api.stock_api import format_stock_info, format_top_stocks, format_market_summary
print(format_stock_info("VCB"))
# print(format_top_stocks("up", 5))
# print(format_top_stocks("down", 5))
print(format_market_summary())

📊 **VCB** — Giá hiện tại: 63,900.0 VNĐ
• Mở cửa: 63,700.0 | Cao nhất: 68,100.0 | Thấp nhất: 59,300.0
• Thay đổi: +200.00 (+0.31%)
• Khối lượng: 1,120,700
🕒 Cập nhật: 08-10-2025 09:38:08
📊 **TỔNG QUAN THỊ TRƯỜNG VIỆT NAM**
📈 **VNINDEX**: 1,696.17 điểm (+10.87, +0.64%)

📊 **Top cổ phiếu tăng mạnh**
🔺 BTH (172247.81%)
🔺 TCO (11900.59%)
🔺 VNI (8736.93%)

📊 **Top cổ phiếu giảm mạnh**
🔻 PTC (-99.96%)
🔻 TOP (-99.67%)
🔻 HTP (-98.51%)
🕒 Cập nhật: 08-10-2025 09:38:15

In [1]:
from modules.api.stock_api import get_time_vn, get_history_df_vnstock, get_prices_df, get_close_series

print("Now ICT:", get_time_vn())  # vd: 20-10-2025 10:12:34

df = get_history_df_vnstock("VCB")
print(df.index.min(), "→", df.index.max())
display(df.tail(3))

dfm = get_prices_df("VCB", days=365)
display(dfm.tail(3))

s = get_close_series("VCB", days=365)
print("len:", len(s), "last:", s.index.max())

Now ICT: 20-10-2025 07:43:01
2024-10-15 00:00:00 → 2025-10-17 00:00:00

            open  high   low  close     volume
_dt
2025-10-15  63.1  63.4  62.5   62.5  5224622.0
2025-10-16  62.7  63.0  62.5   62.9  4634400.0
2025-10-17  62.9  62.9  61.8   61.9  5405900.0

            open  high   low  close     volume
_dt
2025-10-15  63.1  63.4  62.5   62.5  5224622.0
2025-10-16  62.7  63.0  62.5   62.9  4634400.0
2025-10-17  62.9  62.9  61.8   61.9  5405900.0

len: 365 last: 2025-10-17 00:00:00

In [6]:
from vnstock import Quote
raw = Quote(symbol="VCI").intraday()
print(raw.head(), "\n", raw.dtypes, "\n", raw.columns)

                       time  price  volume match_type         id
0 2025-10-27 09:16:13+07:00   37.9    1000       Sell  387214304
1 2025-10-27 09:16:13+07:00   37.9     200       Sell  387214305
2 2025-10-27 09:16:17+07:00   37.9     200       Sell  387214653
3 2025-10-27 09:16:19+07:00   37.9     100        Buy  387214786
4 2025-10-27 09:16:29+07:00   37.9     500        Buy  387215615
 time          datetime64[ns, Asia/Ho_Chi_Minh]
price                                  float64
volume                                   int64
match_type                              object
id                                      object
dtype: object
 Index(['time', 'price', 'volume', 'match_type', 'id'], dtype='object')

In [5]:
from modules.api.stock_api import get_intraday_df
df1 = get_intraday_df("VCI", interval="1m", days=1, debug=True)
print(df1.tail(5))

                      open   high    low  close   volume
time
2025-10-27 09:16:00  38.00  38.00  37.85  37.90  18700.0
2025-10-27 09:17:00  37.90  37.90  37.80  37.90  71300.0
2025-10-27 09:18:00  37.85  37.85  37.80  37.80  62000.0
2025-10-27 09:19:00  37.85  37.85  37.85  37.85    500.0

In [7]:
# tests/test_stock_realtime.py
import pprint
from modules.api.stock_api import (
    get_stock_quote,
    get_history_prices,
    format_stock_info,
    format_history_text,
)

TEST_SYMBOL = "FPT"  # bạn có thể đổi sang HPG, FPT, VNM, SSI,...

def test_realtime_quote():
    print("=== [TEST] Giá hiện tại ===")
    data = get_stock_quote(TEST_SYMBOL)
    pprint.pprint(data)

    print("\n--- Format stock info ---")
    print(format_stock_info(TEST_SYMBOL))
    print("\n")

def test_history_5d():
    print("=== [TEST] Lịch sử 5 ngày ===")
    hist = get_history_prices(TEST_SYMBOL, days=5)
    pprint.pprint(hist)

    print("\n--- Format history text ---")
    print(format_history_text(TEST_SYMBOL, 5, hist))
    print("\n")

if __name__ == "__main__":
    test_realtime_quote()
    test_history_5d()

=== [TEST] Giá hiện tại ===
{'change': -700.0,
 'fallback': False,
 'high': 104500.0,
 'low': 90900.0,
 'market_date': '27-10-2025',
 'open': 97700.0,
 'percent_change': -0.72,
 'price': 97000.0,
 'source': 'VNStock.Trading',
 'symbol': 'FPT',
 'timestamp': '27-10-2025 09:19:48',
 'volume': 646800}

--- Format stock info ---
📊 **FPT** — Giá hiện tại: 97,000.0 VNĐ
• Mở cửa: 97700.0 | Cao nhất: 104500.0 | Thấp nhất: 90900.0
• Thay đổi: -700.00 (-0.72%)
• Khối lượng: 646,800
🕒 Truy vấn lúc: 27-10-2025 09:19:48


=== [TEST] Lịch sử 5 ngày ===
{'days': 5,
 'history': [{'change': 6.0,
              'close': 93.0,
              'date': '21-10-2025',
              'high': 93.0,
              'low': 88.5,
              'open': 89.0,
              'pct_change': 6.9,
              'volume': 19520200},
             {'change': 4.0,
              'close': 97.0,
              'date': '22-10-2025',
              'high': 99.0,
              'low': 95.0,
              'open': 95.2,
              'pct_change': 4.3,
              'volume': 18311100},
             {'change': -2.0,
              'close': 95.0,
              'date': '23-10-2025',
              'high': 97.3,
              'low': 94.0,
              'open': 97.2,
              'pct_change': -2.06,
              'volume': 6647600},
             {'change': 2.7,
              'close': 97.7,
              'date': '24-10-2025',
              'high': 97.7,
              'low': 94.7,
              'open': 95.0,
              'pct_change': 2.84,
              'volume': 13759100},
             {'change': -0.7,
              'close': 97.0,
              'date': '27-10-2025',
              'high': 99.0,
              'low': 96.8,
              'open': 99.0,
              'pct_change': -0.72,
              'volume': 645800}],
 'source': 'VNStock.Quote(FallbackOK)',
 'symbol': 'FPT',
 'timestamp': '27-10-2025 09:19:49'}

--- Format history text ---
📜 **FPT — lịch sử 5 ngày**
• Từ 21-10-2025 → 27-10-2025
• Đóng cửa: 93.00 → 97.00 (**+4.30%**)
• Bản đầy đủ gồm 5 phiên (OHLC, khối lượng).

In [3]:
# tests/test_intraday_and_momentum.py
import numpy as np
from modules.api.stock_api import get_intraday_df

TEST_SYMBOL = "VCB"

def test_intraday_momentum():
    print("=== [TEST] Intraday momentum ===")

    df = get_intraday_df(TEST_SYMBOL, interval="5m", days=1, debug=True)
    if df is None or df.empty:
        print("❌ Không có intraday data.")
        return

    print("OHLCV tail:")
    print(df.tail())

    close = df["close"].astype("float64").dropna()
    if len(close) < 6:
        print("Không đủ nến để tính momentum 5 bước.")
        return

    # log-return giữa các nến
    ret = np.log(close / close.shift(1)).dropna()
    last_returns = ret.tail(5)
    mu = float(last_returns.mean())
    sigma = float(last_returns.std() or 0.0)

    last_px = float(close.iloc[-1])

    print("\n--- Momentum stats ---")
    print(f"ret mean (5 nến cuối): {mu:.6f}")
    print(f"ret std  (5 nến cuối): {sigma:.6f}")
    print(f"last_px: {last_px:.3f}")

    # giả sử giữ nguyên drift mu cho 3 bước tiếp
    step_prices = []
    cur = last_px
    for i in range(3):
        cur = cur * np.exp(mu)
        step_prices.append(cur)

    print("\nDự phóng 3 bước tiếp theo (giả định momentum giữ nguyên):")
    for i,px in enumerate(step_prices, start=1):
        print(f"t+{i}: {px:.3f}")

if __name__ == "__main__":
    test_intraday_momentum()

=== [TEST] Intraday momentum ===
OHLCV tail:
                     open  high   low  close   volume
time
2025-10-27 09:15:00  60.0  60.0  59.7   59.8  41900.0
Không đủ nến để tính momentum 5 bước.